.TH Erikbot 7 "15th June 2012" "Version 1.0"
.SH NAME
Erikbot - A simple IRC Bot
.SH SYNOPSIS
Run through terminal by compiling with g++ or use the makefile.
.SH DESCRIPTION
It's an irc bot, duh. Can connect to a server of your choice. Joins channel #Erikbot. Answers to "hi erikbot" via channel message or query.
.SH OPTIONS
No options yet, sorry.
.SH BUGS
Didn't encounter any in this version so far.
.SH AUTHOR
Erik Fietz - erik.fietz@fh-heidelberg.de
